/* eslint-disable prettier/prettier */
import {
  StyleSheet
} from 'react-native';
const styles = StyleSheet.create({
  mainBody: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    alignContent: 'center',
  },
  scrollView: {
    flex: 1,
    
  },
  topStyle: {
    backgroundColor: '#fff',
    height: 96,
    alignContent: 'center',
    paddingTop: 39,
    paddingBottom: 30,
    borderColor: '#EBEBEB',
    borderBottomWidth: 1,
    position: 'relative',
  },
  buttonClose: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 79,
    height: 96,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextStyle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 18,
    color: '#1D1D25',
  },
  centerStyle: {
    alignContent: 'center',
  },
  sectionStyle: {
    flexDirection: 'column',
    marginTop: 20,
    marginLeft: 16,
    marginRight: 16,
    margin: 10,
  },
  buttonStyle: {
    backgroundColor: '#1D1D25',
    borderWidth: 0,
    color: '#FFFFFF',
    height: 65,
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 25,
    width: '100%',
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 20,
    fontFamily: 'Helvetica-Bold',
    fontWeight: 'bold',
    fontSize: 16,
  },
  inputTitleStyle: {
    color: '#7E797F',
    fontSize: 12,
    marginBottom: 10,
  },
  inputStyle: {
    paddingLeft: 0,
    paddingRight: 0,
    color: '#1D1D25',
    paddingTop: 30,
    paddingBottom: 30,
    fontFamily: 'Helvetica-Bold',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderLeftWidth: 0,
    borderRightWidth: 0,
    marginBottom: 48,
    opacity: 1,
    width: '100%',
  },
  profileBtnStyle:{
    borderRadius:10,
    backgroundColor: '#212129',
    marginBottom: 40,
    width:'45%',
    paddingTop:24,
    paddingBottom:24,
    paddingLeft:22,
    paddingRight:18,
  },
  profileBtn:{
    // color: '#1D1D25',
    color: '#ffffff',
    fontSize: 14,
    opacity: 1,
  },
  profileBtnImgStyle:{
    width: '100%',
    height:42,
  },
  bottomStyle: {
    alignItems: 'center',
    marginBottom: 30,
  },
  copyrightTextStyle: {
    color: '#7E797F',
    textAlign: 'center',
    fontWeight: 'light',
    fontSize: 10,
    alignSelf: 'center',
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
  },
  modalTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 28,
    marginBottom: 25,
    color: '#1D1D25',
  },
  modalSubtitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 24,
    marginBottom: 19,
    color: '#1D1D25',
  },
  modalName: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 18,
    marginBottom: 10,
    color: '#1D1D25',
  },
  modalDate: {
    fontFamily: 'Helvetica',
    fontSize: 14,
    marginBottom: 10,
    color: '#959595',
  },
  modalDate2: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 14,
    marginBottom: 10,
    color: '#1D1D25',
  },
  modalDesc: {
    fontFamily: 'Helvetica',
    fontSize: 16,
    marginBottom: 25,
    color: '#1D1D25',
    textAlign: 'center',
  },
  notificationIcon: {
    width: 18,
    height: 21,
    position: 'absolute',
    top: 40,
    right: 37,
  },
  notificationImg: {
    width: 18,
    height: 21,
  },
  notificationNumber: {
    width: 15,
    height: 15,
    backgroundColor: '#FF9D9D',
    borderRadius: 13,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    top: -30,
    right: -7,
  },
  notificationText: {
    fontSize: 10,
    lineHeight: 10,
    fontFamily: 'Helvetica-Bold',
    color: '#fff',
  },
  borderedInputTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 14,
    color: '#1D1D25',
  },
  borderedInput: {
    borderWidth: 1,
    padding: 20,
    fontSize: 12,
    borderRadius: 10,
    height: 54,
    color: '#1D1D25',
    marginBottom: 18,
  },
  appBtn: {
    width: '19%',
    height: 60,
  },
  linearGradient: {
    flex: 1,
  },
  discoverTitleText: {
    fontSize: 16,
    fontFamily: 'Gill Sans',
    fontWeight:'500',
    color: '#0B1929',
    backgroundColor: 'transparent',
  },
});
export {
  styles
};