import React from 'react';
import { ScrollView, Text, StyleSheet, View } from 'react-native';
import { legalStyles } from "../Components/LegalStyles";

const PayfourUyelikVeKullaniciSozlesmesi = () => {
  return (
    <View style={legalStyles.container}>
      <View style={legalStyles.section}>
{/* <Text style={legalStyles.title}>CARREFOURSA PAYFOUR ÜYELİK VE KULLANICI SÖZLEŞMESİ</Text>*/}
</View> 

<Text style={legalStyles.subtitle}>1. TARAFLAR</Text>
<Text style={legalStyles.paragraph}>İşbu Üyelik ve Kullanıcı Sözleşmesi (“Sözleşme”); “Payfour” isimli uygulamasının sahibi olan ve “CarrefourSA Plaza Cevizli Mah. Tugay Yolu Cad. No:67/A Blok:B Maltepe/İstanbul” adresinde bulunan CarrefourSA Carrefour Sabancı Ticaret Merkezi Anonim Şirketi ("CarrefourSA” ve/veya “Şirket”) ile aşağıdaki şartları kabul ederek uygulamaya üye olan kullanıcı (“Üye”) arasında, Üye’nin Uygulama’dan yararlanmasına ilişkin koşulların belirlenmesi adına akdedilmiştir. </Text>
<Text style={legalStyles.paragraph}>CarrefourSA ve Üye, işbu Sözleşme’de ayrı ayrı “Taraf”, birlikte “Taraflar” olarak anılacaktır. </Text>

<Text style={legalStyles.subtitle}>2. TANIMLAR </Text>
<Text style={legalStyles.paragraph}>Uygulama: Payfour isimli uygulamadır.</Text>
<Text style={legalStyles.paragraph}>Üye ve/veya Kullanıcı: CarrefourSA’dan ve/veya anlaşmalı iş ortaklarından ürün ve/veya hizmet alımı yapmak üzere faydalanmak isteyen, Üyelik Formu’nu (“Form”) eksiksiz doldurarak, CarrefourSA tarafından üyelikleri onaylanarak, kabul edilen gerçek kişidir.</Text>
<Text style={legalStyles.paragraph}>18 (on sekiz) yaşını doldurmuş olan Kullanıcılar, gerçek kimlik bilgileri ile Uygulama’daki Form’u eksiksiz doldurarak üye olabilirler. "Üye Adı", her bir üyeye özeldir ve aynı "Üye Adı" iki farklı Üye'ye verilmez. </Text>
<Text style={legalStyles.subtitle}>3. SÖZLEŞME’NİN KONUSU</Text>
<Text style={legalStyles.paragraph}>İşbu Sözleşme’nin konusu, CarrefourSA tarafından Üye’nin aktive edilmesi tarihinden itibaren sunacağı hizmetler Üye’nin Uygulama kullanımının haklarını ve yükümlülüklerini kapsamaktadır. Üye, işbu Sözleşme’yi imzalayarak tüm yükümlülüklerini bildiğini kabul, beyan ve taahhüt etmektedir.  Sözleşme uyarınca Üye, Uygulama’ya üye olarak hizmetler’den faydalanmayı talep etmektedir.</Text>
<Text style={legalStyles.paragraph}>Üye, işbu Sözleşme’yi kabul etmekle birlikte Uygulama içeriklerine, hesaba, ürün ve hizmetlere ilişkin Şirket tarafından yayınlanan tüm beyana uygun davranacağını kabul, beyan ve taahhüt etmektedir.</Text>
<Text style={legalStyles.paragraph}>Üyelik başvurusu Şirket tarafından herhangi bir sebep gösterilmeksizin reddedilebilir veya ek şart ve koşullar talep edilebilir. Uygulama’ya üye olabilmek için, varsa, önceki üyeliklerin herhangi bir sebeple iptal edilmemiş olması gerekir. Üyeliğin daha önceden herhangi bir nedenle iptal edilmiş olması halinde Sözleşme’nin Üye tarafından onaylanması üyelik sonucunu doğurmaz ve Şirket tek taraflı olarak üyelik talebini reddetme hakkını haizdir.</Text>
<Text style={legalStyles.paragraph}>Şirket herhangi bir gerekçe göstermeksizin ve/veya herhangi yazılı ya da sözlü bildirimde bulunmaksızın derhal yürürlüğe girecek şekilde ve tazminat, ceza vb. sair yükümlülüğü bulunmaksızın Üye’nin üyeliğini her zaman tek taraflı olarak sonlandırabilir, dondurabilir veya Üye’nin Uygulama’ya erişimini kısıtlayabilir ve/veya engelleyebilir.</Text>
<Text style={legalStyles.subtitle}>4. UYGULAMA’DA SUNULAN ÜRÜN ve/veya HİZMETLER </Text>
<Text style={legalStyles.paragraph}>4.1.	CarrefourSA Uygulama’da sunulan ürün ve/veya hizmetleri bizzat kendisi sunabileceği gibi üçüncü kişi iş ortakları aracılığıyla da sunabilir. Uygulama’da Üye’ye sunulan hizmetlere işbu Sözleşme dışında üçüncü bir kişi veya kurumun taraf olması halinde, bu kişi veya kurumun kendi kapsam ve koşullarını belirleme hakkı saklıdır. CarrefourSA, üçüncü kişi iş ortakları üzerinden sunulan ürün ve/veya hizmetlere ilişkin Uygulama’da açıkça belirtilmediği sürece garanti vermemektedir.</Text>
<Text style={legalStyles.paragraph}>4.2.	Payfour, Şirket’in CarrefourSA Kart’lı üyelerine sunduğu ek bir uygulamadır. Payfour Üye’si olabilmek için öncelikle CarrefourSA Kart üyesi olunmalıdır.</Text>
<Text style={legalStyles.paragraph}>4.3.	Sözleşme kapsamında Üye’ye sunulan hizmetlerin kapsamı, Şirket tarafından herhangi bir zamanda ve tek taraflı olarak herhangi bir bildirimde bulunma zorunluluğu olmadan genişletilebilir veya daraltılabilir.</Text>
<Text style={legalStyles.paragraph}>4.4.	Şirket, Uygulama üzerinden Kullanıcı’larına alışveriş kredisi temin etme, temin ettiği alışveriş kredisini kullanma ve kredi limitini öğrenme imkanı hizmetleri sunmaktadır.</Text>
<Text style={legalStyles.paragraph}>4.5.	Şirket, işbu hizmetleri “olduğu gibi”, “tüm hataları ile birlikte” ve “kullanıma sunulduğu haliyle” vermektedir. Şirket, hizmetler ile ilgili herhangi bir açık veya örtülü garanti veya teminat veya sınırsız ve eksiksiz bir hizmet taahhüdü vermemektedir. Bu bağlamda, CarrefourSA herhangi bir servis seviyesi ve/veya güvenlik seviyesi de garanti etmemektedir. Bu kapsamda CarrefourSA;</Text>
<Text style={legalStyles.subtitle}> - Üye’nin Uygulama’yı ve hizmetleri kullanması, kullanmaması veya yanlış kullanmasından,</Text>
<Text style={legalStyles.subtitle}> - Yazılım, donanım ve ağ ilişkili işlevden ve bu nedenle ortaya çıkacak arızalardan,</Text>
<Text style={legalStyles.subtitle}> - İnternet bağlantısı, iletişim ağı (network) hatalarından,</Text>
<Text style={legalStyles.subtitle}> - Uygulama üzerinde gerçekleştirilecek güncelleme ve benzeri çalışmalar sonucunda oluşabilecek hata ve arızalardan,</Text>
<Text style={legalStyles.paragraph}>yukarıda sayılanlarla sınırlı olmaksızın Üye’lerin Uygulama’yı kullanmasını engelleyen uyumsuzlukların veya hataların ortaya çıkmasından kaynaklanan tüm zararlardan, her türlü kar kaybı, veri kaybı, iş kaybı, itibar kaybı, beklenen tasarrufun kaybı, işin kesintiye uğraması gibi her türlü maddi, manevi ve mali zararlardan, bu kapsamda üçüncü bir tarafça yapılabilecek tazminat taleplerinden sorumlu değildir.</Text>
<Text style={legalStyles.subtitle}>5. TARAFLAR’IN HAK VE YÜKÜMLÜLÜKLERİ</Text>
<Text style={legalStyles.paragraph}>5.1.	 Üyelik statüsünün kazanılması için, Üye olmak isteyen Kullanıcı’nın, Uygulama’da yer alan işbu Sözleşme’yi onaylayarak talep edilen bilgileri doğru ve güncel olarak doldurması ve üyelik başvurusunun CarrefourSA tarafından onaylanması gerekmektedir. Onaylanma işlemi akabinde işbu husus Üye’ye bildirilecek ve Üyelik statüsü başlayacaktır. Böylece Üye, Sözleşme ve Uygulama’nın ilgili yerlerinde belirtilen haklardan yararlanabilecek ve yükümlülüklerden sorumlu hale gelecektir. </Text>
<Text style={legalStyles.paragraph}>5.2.	Üye olmak isteyen Kullanıcı’nın, 18 (on sekiz) yaşını doldurmuş olması aranacaktır. 18 (on sekiz) yaşını doldurmamış kişiler, Uygulama’dan yararlanamazlar. Uygulama’ya üye olmakla, kişi, 18 (on sekiz) yaşından büyük olduğunu beyan ve kabul eder.</Text>
<Text style={legalStyles.paragraph}>5.3.	Üye, Uygulama üzerinde gerçekleştirdiği işlemlerde ve yazışmalarda, işbu Sözleşme’nin hükümlerine, Uygulama’da belirtilen tüm koşullara, yürürlükteki mevzuata ve ahlak kurallarına uygun olarak hareket edeceğini kabul ettiğini beyan eder. Üye'nin Uygulama dâhilinde yaptığı işlem ve eylemlere ilişkin hukuki ve cezai sorumluluk kendisine aittir.</Text>
<Text style={legalStyles.paragraph}>5.4.	Üye, Form’da bildirdiği veya daha sonra kendisi tarafından güncellenen adres, e-posta adresi, telefon hatları ve diğer iletişim bilgilerinin kanunlar önünde doğru olduğunu, Şirket’in bu bilgilerin gerçeğe aykırılığı nedeniyle uğradığı tüm zararları aynen ve derhal tazminle mükellef olduğunu, bildirmiş olduğu bilgiler üzerinden e-posta, SMS, telefon görüşmesi ve diğer yollarla Üye’ye iletişim, pazarlama, bildirim ve diğer amaçlarla CarrefourSA’nın kendisine ulaşma hakkı bulunduğunu, aksine bir yazılı bildirim yapılmadığı müddetçe işbu Sözleşme’nin onaylanması ile Şirket’in yukarıda sayılan iletişim faaliyetlerini gerçekleştirmek amacıyla kendisi ile iletişime geçebileceğini, bilgilerini kendi pazarlama faaliyetleri çerçevesinde kullanabileceğini, Kişisel Verilerin Korunması kanunu çerçevesinde üçüncü kişilerle paylaşabileceğini kabul eder. </Text>
<Text style={legalStyles.paragraph}>5.5.	Üye, diğer üyelerin şifrelerinin ve e-posta adreslerinin kendilerine özel ve gizli olduğunu ve bunlara izinsiz erişip kullanması halinde doğacak her türlü hukuki ve cezai sorumluluğun münferiden Üye’ye ait olacağını, kabul, beyan ve taahhüt eder.</Text>
<Text style={legalStyles.paragraph}>5.6.	Üye, Sözleşme süresince ve sonrasında, Uygulama ile ilgili hiçbir bilgi, şifre veya kodu üçüncü bir kişi veya kuruluşa vermeyeceğini taahhüt eder. Bu bilgilerin üçüncü bir kişi veya kuruluşa verildiğinin tespit edilmesi halinde, Şirket, Sözleşme’yi derhal feshetme hakkına sahiptir. Böyle bir durumda Üye, Şirket’in ve üçüncü kişilerin bu ihlalden doğan her tür zararından kendisinin münhasıran sorumlu olacağını kabul, beyan ve taahhüt eder.</Text>
<Text style={legalStyles.paragraph}>5.7.	Uygulama’da ve bulunması halinde uzantılarında yer alan ticari markalar, ticari unvanlar, başlıklar, logolar, grafikler, desenler, görseller, genel görünüm, ticari takdim şekli, metinler ve Uygulama’da kullanılan tüm diğer materyaller, teknik veriler yetkisinin Şirket’e veya Şirket’in kullanım hakkı veya yetkisi elde ettiği grup şirketlerine aittir ve yasal koruma altındadır. Uygulama üzerinde sunulan metin ve grafik dosyaları copyright ve/veya müseccel marka kanunlarıyla ya da başka herhangi bir yolla CarrefourSA’ya ait fikri mülkiyet haklarıyla korunmaktadır. Bu sebeple Uygulama ve varsa uzantılarında yer alan ve yukarıda sayılı her metin ya da görsel materyal dahil, hiçbir unsur önceden izin alınmaksızın kullanılamaz. Bu Uygulama’da yer alan hiçbir materyal ve fonksiyonalite, Şirket’in izni olmadan, başka mecralarda yayınlanamaz, kopyalanamaz, çoğaltılamaz, değiştirilemez, tekrar üretilemez, başka bir lisansa çevrilemez, posta ile gönderilemez, bilgisayara yüklenip her ne amaçla olursa olsun kullanılamaz, link veremez, başka internet sitelerinde kullanılamaz. Bu sayılanlar dışında bulunan diğer tüm haklar saklı tutulmakla beraber bu sayılanlara aykırı hareket edilmesi halinde Şirket her türlü hukukî ve cezaî yola başvurma hakkına sahip bulunmaktadır. Üye, tüm bu hususları bildiğini kabul ve beyan eder. </Text>
<Text style={legalStyles.paragraph}>5.8.	Şirket tarafından gerekli özenin gösterilmesine rağmen Şirket’in elinde olmayan sebeplerden dolayı ortaya çıkan fiyat değişikliği ve benzeri durumlardan, Şirket’in herhangi bir hukuki, idari veya cezai sorumluluğu bulunmamaktadır.</Text>
<Text style={legalStyles.paragraph}>5.9.	Uygulama üzerinden, Şirket’in sahibi olmadığı internet site/sitelerine bağlantı verilmesi halinde; Şirket’in işbu site/sitelerin içerikleri ve/veya içerdikleri bağlantılardan, hiçbir hal ve surette hukuki, cezai, idari ve başkaca sorumluluğu bulunmamaktadır. İşbu bağlantılı sitelere giriş halinde doğabilecek risklerin ve oluşabilecek her türlü zararın tamamen Üye ve Kullanıcılara ait olduğunu Üye’ler bilmekte, kabul ve beyan etmektedir. </Text>
<Text style={legalStyles.paragraph}>5.10. Şirket’in her ne sebeple olursa olsun üyelik işleminin kesintiye uğraması, silinmesi, kaybolması, işlemde gecikme yaşanması, bilgisayar virüsü kapılması, izinsiz olarak kayıtlara girilmesi, hırsızlık, kayıtların değiştirilmesi veya kullanılması hususunda hiçbir sorumluluğu bulunmamaktadır.</Text>
<Text style={legalStyles.paragraph}>5.11. Üye, hizmetlere ilişkin finansal işlemleri ve ödemeleri Uygulama’da kendisine sunulanlar içinden seçtiği yöntem ile gerçekleştirebilir. Bu finansal işlemlerde ve ödemelerde, hesabın sahibi veya kartın hamili haricinde bir başkası tarafından hukuka aykırı şekilde kullanılması halinde ilgili mevzuat hükümlerine göre işlem yapılır. Uygulama, hiçbir şekilde kredi kartı veya hesap bilgisi gibi ilgili mevzuat düzenlemeleri uyarınca yetkilendirilmiş kurum ve kuruluşlar tarafından işlenebilecek verileri toplamaz. Bu bilgilerin işlenmesinden münhasıran yetkili kurum ve kuruluşlar sorumludur. </Text>
<Text style={legalStyles.paragraph}>5.12. Uygulama’ya hatalı, eksik ve yanıltıcı, genel ahlak kuralları ile kamu düzenine ve Türkiye Cumhuriyeti hukuk kurallarına aykırı bilgiler ve ifadeler girildiğinin, işletim sisteminin güvenliğini tehdit edici nitelikte faaliyete girişildiğinin, Uygulama içeriğindeki bilgilerin değiştirilmeye, silinmeye çalışıldığının ve buna benzer durumların tespit edilmesi halinde Üye’nin Uygulama’ya erişim hakkı Şirket tarafından engellenebilecek, Üye’lik askıya alınabilecektir. Bu gibi faaliyetlere karışan kişiler hakkında, Şirket’in Sözleşme’yi tek taraflı olarak feshetme hakkı dahil olmak üzere her türlü hukuki ve cezai hakkı saklı tutulmaktadır.</Text>
<Text style={legalStyles.paragraph}>5.13. Üye'nin Uygulama üzerinden işlem gerçekleştirebilmek adına ihtiyaç duyduğu kullanıcı adı ve şifre bilgisi, Üye tarafından oluşturulmakta olup söz konusu bilgilerin güvenliği ve gizliliği tamamen Üye'nin sorumluluğundadır. Üye, kendisine ait kullanıcı adı ve şifre ile gerçekleştirilen işlemlerin kendisi tarafından gerçekleştirilmiş olduğunu, bu işlemlerden kaynaklanan sorumluluğunun peşinen kendisine ait olduğunu, bu şekilde gerçekleştirilen iş ve işlemleri kendisinin gerçekleştirmediği yolunda herhangi bir def'i ve/veya itiraz ileri süremeyeceğini ve/veya bu def'i veya itiraza dayanarak yükümlülüklerini yerine getirmekten kaçınmayacağını kabul, beyan ve taahhüt eder. Üye’nin, üyelik adı ve şifresi gibi bilgileri üçüncü kişi ve kuruluşlarla paylaşma, diğer üyelerin bilgilerine ulaşma ve kullanma hakkı bulunmamaktadır. Üye’nin söz konusu aykırı hareketinden kaynaklanan her türlü zarardan Üye tek başına sorumludur. Bu tür kullanımlardan kaynaklanan her türlü hukuki, idari ve cezai sorumluluk Üye’ye ait olacaktır.</Text>
<Text style={legalStyles.paragraph}>5.14. Üye’ler Uygulama’yı kullanırken Şirket’in Uygulama’da sunulan hizmetlere ilişkin olarak yayınlayacağı bildirimlere, başta Türk Ceza Kanunu, Türk Borçlar Kanunu, Türk Medeni Kanunu, Türk Ticaret Kanunu, Fikir ve Sanat Eserleri Kanunu, Sınai Mülkiyet Kanunu olmak üzere her türlü yasal düzenlemeye uygun davranmayı; aykırı kullanım halinde hukuki, cezai ve idari her türlü sorumluluğun Üye’ye ait olacağını beyan, kabul ve taahhüt eder.  </Text>
<Text style={legalStyles.paragraph}>5.15. Şirket’in, Üye’leri ve Kullanıcılarının işbu Sözleşme ile sayılan yükümlülüklere ve/veya burada sayılı olmamakla beraber işbu Sözleşme’de yer alan tüm Kullanım Koşulları’na uygun davranmadığının tespiti halinde Üye’nin Uygulama kullanımını süreli/süresiz engelleme ve/veya hesabını kapatma, Sözleşme’yi tek taraflı olarak feshetme hakkı bulunmaktadır.</Text>
<Text style={legalStyles.paragraph}>5.16. Üye, işbu Sözleşme ile üstlenmiş olduğu yükümlülüklere aykırı hareketi ve/veya haksız fiili nedeniyle Şirket’in uğrayacağı her türlü zararı aynen tazmin etmeyi, Üye’nin Sözleşme’ye aykırı davranışları nedeniyle Şirket’in kamu kurumlarına ve/veya üçüncü şahıslara ödemek zorunda kalabileceği her türlü tazminat ve/veya idari, adli para cezaları için Üye’ye aynen rücu hakkı bulunduğunu beyan, kabul ve taahhüt eder.</Text>
<Text style={legalStyles.paragraph}>5.17. Üye’nin Uygulama’nın çalışmasına müdahale etmek veya müdahaleye teşebbüs etmek amacıyla herhangi bir alet, yazılım veya araç kullanması, yetkisiz olarak bağlanması veya diğer Üye’lerin yazılımlarına ve verilerine izinsiz ulaşması durumunda Şirket ilgili Üye’nin üyeliğini geçici olarak askıya alabilir veya tamamen iptal edebilir. Bu durumda Şirket’in Üye’ye yönelik olarak her türlü talep ve başvuru hakkı saklıdır.</Text>
<Text style={legalStyles.paragraph}>5.18. Üye, üyeliğini iptal etmek istemesi halinde ilgili talep, uygulama içerisindeki “Hesabımı sil” butonu veya 444 10 00 telefon numarası üzerinden CarrefourSA’ya bildirmelidir. Üyeliğin iptal edilmesi halinde Üye olarak Uygulama’ya giriş yetkisi kaldırılacaktır.</Text>
<Text style={legalStyles.paragraph}>5.19. Üyelerin, Şirket ile yaptığı her türlü yazışmanın saklanması tamamen onların sorumluluğunda olup işbu yazışmaların silinmesi ve/veya kaybolmasından Şirket hiçbir hak ve surette sorumlu tutulamaz. </Text>
<Text style={legalStyles.paragraph}>5.20. Üye’nin hesabını sonlandırması halinde Şirket hesaba ilişkin bilgileri kişisel verilerin korunması kanunu çerçevesinde silme/silmeme, üçüncü kişilerle paylaşma/paylaşmama hakkını saklı tutar. Üye’nin bu halde Şirket’ten hiçbir hal ve surette hak ve tazminat isteme hakkı bulunmamaktadır. </Text>
<Text style={legalStyles.paragraph}>5.21. Şirket, tamamen kendi takdirine bağlı olmak üzere, işbu Sözleşme hükümlerinde ve Uygulama’da yer alan Üyelik Aydınlatma Metni dahil her türlü politikayı, hüküm ve şartı uygun göreceği herhangi bir zamanda, önceden Üye’ye bildirimde bulunmaksızın tek taraflı olarak sonrasında ilan ederek değiştirebilir. Şirket, Üye’lere sağlanan hizmetleri sürekli/geçici olarak durdurma, içeriğini değiştirme hakkını saklı tutar. İşbu Sözleşme’nin değişen hükümleri, Uygulama’da ilan edildikleri tarihte geçerlilik kazanacak, geri kalan hükümler aynen yürürlükte kalarak hüküm ve sonuçlarını doğurmaya devam edecektir.</Text>
<Text style={legalStyles.paragraph}>5.22. Şirket, yürürlükteki mevzuat uyarınca yetkili makamların talebi halinde, Üye'nin kendisinde bulunan bilgilerini söz konusu makamlarla paylaşabilecektir.</Text>
<Text style={legalStyles.paragraph}>5.23. Uygulama’ya üyelik sırasında ve/veya alışveriş sırasında Üye’lerden alınan kişisel veriler, sahtecilik, dolandırıcılık, Uygulama’nın kötüye kullanımı, Türk Ceza Kanunu anlamında suç oluşturabilecek konularda çıkan uyuşmazlıklarda, yalnızca talep edilen konu ile sınırlı olmak üzere tarafların yasal haklarını kullanabilmeleri amacıyla ve sadece bu kapsam ile sınırlı olmak üzere uyuşmazlığa taraf olabilecek diğer Üye’lere iletebilecektir.</Text>
<Text style={legalStyles.subtitle}>6. GİZLİLİK ve KİŞİSEL VERİLERİN KORUNMASI</Text>
<Text style={legalStyles.paragraph}>6.1.	Şirket, Üye'nin Uygulama’da sunulan hizmetlerden yararlanabilmek için Uygulama üzerinden kendisine sağladığı kişisel verilerin 6698 sayılı Kişisel Verilerin Korunması Kanunu da dahil her türlü mevzuata uygun bir şekilde işlenmesine, güvenliğinin sağlanmasına ve korunmasına önem vermektedir. Şirket, bu kapsamda Üye'nin sağladığı kişisel verileri uygulamada yer alan Üyelik Aydınlatma Metni başta olmak üzere Uygulama’da yer alan kişisel verilerin korunmasına ilişkin diğer aydınlatma metinleri ve politikalara uygun olarak toplamakta, kullanmakta, aktarmakta ve diğer şekillerde işleyebilmektedir. Üyelik Aydınlatma Metni, işbu Sözleşme’nin ayrılmaz bir parçasıdır.</Text>
<Text style={legalStyles.paragraph}>6.2.	Üye, hizmetlerden faydalanarak ve/veya bir hesap oluşturarak Üyelik Aydınlatma Metni’nde belirlendiği şekilde kişisel verilerinin toplanmasına, kullanılmasına, aktarılmasına ve diğer şekillerde işlenmesine açık bir şekilde ve özgür iradesiyle rıza göstermektedir. </Text>
<Text style={legalStyles.paragraph}>6.3.	Üye tarafından Uygulama’da beyan edilen ve paylaşılmasına rıza gösterilen kişisel veriler; işbu Sözleşme ile belirlenen yükümlülüklerin ifası, Uygulama’nın işletilmesi için gereken uygulamaların yürütülmesi, Üye için çeşitli avantajların sağlanıp sunulabilmesi ve Üye’ye özel reklam, satış, pazarlama, anket, benzer amaçlı her türlü elektronik iletişim, profilleme, istatistiksel çalışmalar yapılması amacıyla Şirket ya da iş ortakları tarafından başta Üyelik Aydınlatma Metni olmak üzere uygulamada bulunan kişisel verilerin korunmasına ilişkin diğer aydınlatma metinleri ile açık rıza beyanlarına uygun olarak toplanır, saklanır, işlenir, kullanılır ve akdi ilişkilere istinaden üçüncü kişilerle paylaşılabilir.</Text>
<Text style={legalStyles.paragraph}>6.4.	Üye, kişisel verilerinin bilgilerinin Şirket tarafından bu şekilde kullanımına ve saklanmasına rıza gösterdiğini kabul ve beyan eder. Şirket, söz konusu kişisel verilerin 6698 Sayılı Kişisel Verilerin Korunması Kanunu’nun 12. maddesi uyarınca güvenli şekilde saklanması, yetkisiz erişimlerin ve hukuka aykırı veri işlemelerin önlenmesi için gereken her türlü tedbiri alacaktır. Üye, kişisel verileri üzerinde 6698 Sayılı Kişisel Verilerin Korunması Kanunu’nun 11. maddesi uyarınca sahip olduğu hakları kullanma ve bu verilerinde dilediği zaman değişiklik veya güncelleme yapma hakkına sahiptir.</Text>
<Text style={legalStyles.paragraph}>6.5.	Üye, Şirket tarafından Sözleşme’de bir değişiklik yapıldığı takdirde yapılan bu değişikliğin Uygulama’da yayımlanacağını, yapılan değişikliklerin Uygulama’da yayımlandığı tarihten itibaren geçerli olacağını bildiğini ve yayım tarihinden itibaren bu kurallara uygun bir biçimde Uygulama’yı kullanmak ve yükümlülüklerini ifa etmekle sorumlu olduğunu kabul, beyan ve taahhüt eder.</Text>
<Text style={legalStyles.subtitle}>7. SÖZLEŞME’NİN DEVRİ</Text>
<Text style={legalStyles.paragraph}>Şirket’in önceden yazılı onayını almaksızın işbu Sözleşme’deki haklarını veya yükümlülüklerini tümüyle veya kısmen temlik edemeyecektir. Aksine bir devir halinde ise Üye, bu hükme aykırılıktan dolayı sorumluluğunun doğacağını ve Şirket’in tek taraflı işbu Sözleşme’yi fesih hakkı olduğunu kabul, beyan ve taahhüt eder.</Text>
<Text style={legalStyles.subtitle}>8. MÜCBİR SEBEP</Text>
<Text style={legalStyles.paragraph}>Ayaklanma, ambargo, devlet müdahalesi, isyan, işgal, savaş, seferberlik, grev, lokavt, iş eylemleri veya boykotlar dahil olmak üzere işçi-işveren anlaşmazlıkları, siber saldırı, iletişim sorunları, altyapı ve internet arızaları, sisteme ilişkin iyileştirme veya yenileştirme çalışmaları ve bu sebeple meydana gelebilecek arızalar, elektrik kesintisi, yangın, patlama, fırtına, sel, deprem, göç, salgın veya diğer bir doğal felaket veya Şirket’in kontrolü dışında gerçekleşen, kusurundan kaynaklanmayan ve makul olarak öngörülemeyecek diğer olaylar ("Mücbir Sebep") Şirket’in işbu Sözleşme’den doğan yükümlülüklerini ifa etmesini engeller veya geciktirirse, CarrefourSA, ifası Mücbir Sebep sonucunda engellenen veya geciken yükümlülüklerinden dolayı sorumlu tutulamaz ve bu durum işbu Sözleşme’nin bir ihlali olarak kabul edilemez.</Text>
<Text style={legalStyles.subtitle}>9. KULLANIM KOŞULLARI</Text>
<Text style={legalStyles.paragraph}>9.1.	 Kullanım Koşulları, iOS ve Android uygulamalarında kullanıma sunulan ve akıllı telefonlara indirilerek kullanılan Uygulama içerisinde yer alan hizmetinin kullanılmasına ilişkin kural ve koşulları belirlemektedir ve bu doğrultuda Taraflar’ın hak ve yükümlülüklerini düzenlemektedir.  </Text>
<Text style={legalStyles.paragraph}>9.2. Payfour, hizmetlerinde Üye’lere işbu Kullanım Koşulları kapsamında içeriği belirlenen hizmetler sağlanacaktır. Payfour ile Ödeme Hizmeti Veren kurumu da bir araya getiren bir uygulamadır. Şirket, bu hizmetlere ilişkin herhangi bir konuda garanti vermemektedir.</Text>
<Text style={legalStyles.paragraph}>9.3. Payfour uygulamasında yer alan kredi hizmetleri nedeniyle ilgili kuruluşun Kredi Sözleşmesi ve sair sözleşmelerinin içeriği ve onaylanması Şirket’in sorumluluğunda değildir. İlgili hizmetler nedeniyle işbu sözleşmelerden doğan herhangi bir ihlalden Şirket’e başvurulamaz ve Şirket’in herhangi bir sorumluluğu bulunmamaktadır. </Text>
<Text style={legalStyles.paragraph}>9.4. CarrefourSA, bu Kullanım Koşulları istediği zaman, herhangi bir bildirimde bulunmaksızın içeriğini değiştirme, güncellemeleri takip etmek Üye’nin sorumluluğundadır. Güncel Kullanım Koşulları, Uygulama’da yayınlandığı andan itibaren geçerli olacaktır. </Text>
<Text style={legalStyles.paragraph}>9.5. Şirket, Üyelik ve Kullanıcı Sözleşmesi ile işbu Kullanım Koşullarını ihlâl etmeniz veya ihlal ettiğine ilişkin şüphe duyması durumunda, hesabınızı askıya alabilir veya Uygulamayı kullanımınızı sonlandırabilir; sağladığınız tüm içerikleri yayından kaldırabilir ve/veya hukuka aykırılık halinde hakkınızda dava veya hukuki takip yoluna başvurabilir. </Text>
<Text style={legalStyles.paragraph}>9.6. Bu Üyelik ve Kullanıcı Sözleşmesi ile işbu Kullanım Koşullarını kabul etmiyorsanız, lütfen uygulamayı kullanmayınız.</Text>
<Text style={legalStyles.paragraph}>9.7. Üye’ler öncelikle Şirket’in CarrefourSA Kart üyeliği sonrasında Uygulama’ya üye olurlar.</Text>
<Text style={legalStyles.paragraph}>9.8. Üye’ler, başvuru esnasında verdiği tüm bilgilerin daima ve her bakımdan eksiksiz, gerçeğe uygun ve güncel olduğunu kabul eder. </Text>
<Text style={legalStyles.subtitle}>10. AYRILABİLİRLİK</Text>
<Text style={legalStyles.paragraph}>İşbu Sözleşme, konuya ilişkin olarak Taraflar arasındaki anlaşmanın tamamını oluşturmaktadır. İşbu Sözleşme’nin herhangi bir hükmünün yetkili herhangi bir mahkeme, tahkim heyeti veya idari makam tarafından tümüyle veya kısmen geçersiz veya uygulanamaz olduğu veya makul olmadığına karar verilmesi halinde, söz konusu geçersizlik, uygulanamazlık veya makul olmama ölçüsünde işbu Sözleşme bölünebilir olarak kabul edilecek ve diğer hükümler tümüyle yürürlükte kalmaya devam edecektir.</Text>
<Text style={legalStyles.subtitle}>11. FESİH</Text>
<Text style={legalStyles.paragraph}>Şirket, herhangi bir sebep göstermeksizin ve tek taraflı olarak her zaman, herhangi bir ihbara ve tazminat ödeme yükümlülüğüne gerek olmaksızın işbu Sözleşme’yi derhal feshedebilir.</Text>
<Text style={legalStyles.subtitle}>12. DELİL</Text>
<Text style={legalStyles.paragraph}>Taraflar, işbu Sözleşme kapsamında doğabilecek ihtilaflarda, Şirket’e ait tüm resmi defter ve ticari kayıtları ile Şirket’in veri tabanında, sunucularında tutulan e-arşiv kayıtlarının, elektronik bilgilerin ve bilgisayar kayıtlarının bağlayıcı, kesin ve münhasır delil teşkil edeceğini ve bu maddenin 6100 sayılı Hukuk Muhakemeleri Kanunu’nun 193. maddesi anlamında delil sözleşmesi niteliğinde olduğunu kabul eder.</Text>
<Text style={legalStyles.subtitle}>13. YETKİLİ MAHKEME</Text>
<Text style={legalStyles.paragraph}>İşbu Sözleşme münhasıran Türkiye Cumhuriyeti kanunlarına tabi olacaktır. İşbu Sözleşme’den kaynaklanan veya işbu Sözleşme ile bağlantılı olan her türlü ihtilaf, İstanbul Tüketici Hakem Heyetleri ve İstanbul Anadolu Mahkemeleri ve İcra Müdürlükleri'nin münhasır yargı yetkisinde olacaktır.</Text>
<Text style={legalStyles.subtitle}>14. BİLDİRİM</Text>
<Text style={legalStyles.paragraph}>14.1. Üye’nin, Şirket’e bildirdiği elektronik posta adresi, bu Sözleşme ile ilgili olarak yapılacak her türlü bildirim için yasal adresin isteneceği elektronik posta olarak kabul edilir. Bu elektronik posta adresinin kullanılarak Üye’ye yapılan her türlü bildirimin, Üye’ye postanın gönderildiği gün ulaştığı kabul edilir.</Text>
<Text style={legalStyles.paragraph}>14.2. Üye, Şirket ile aşağıdaki iletişim kanallarından her zaman irtibata geçebilir. Uygulama’da yer alan ilgili bölümden Şirket’e doğrudan e-posta gönderebilir.</Text>
<Text style={legalStyles.paragraph}>Telefon Numarası	:	444 10 00</Text>
<Text style={legalStyles.paragraph}>E-posta adresi	:	bilgi@carrefoursa.com</Text>
<Text style={legalStyles.subtitle}>15. YÜRÜRLÜK</Text>
<Text style={legalStyles.paragraph}>İşbu Sözleşme, Şirket tarafından üyelik için belirlenen bilgilerin Üye tarafından tam ve hatasız şekilde Şirket ile paylaşılmasını ve Şirket tarafından belirlenen ve başta işbu Sözleşme olmak üzere Uygulama’da yer alan ilgili metinlerin Üye tarafından okunmasını ve elektronik ortamda onaylanmak suretiyle kabul edilmesini takiben Şirket’in ilgili üyeliği onaylaması ile yürürlüğe girer ve Üye’nin üyeliği iptal edilinceye kadar tüm hüküm ve sonuçlarını doğurmaya devam eder. Ayrıca, Üye, kendisiyle ilgili olarak verdiği bilgilerin doğruluğunu onayladığını, bu onaylamadan sonra kendisine gönderilen tüm ticari içerikli gönderilere muvafakati bulunduğunu beyan, kabul ve taahhüt eder.</Text>

    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#FFFFFF',
  },
  header: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 10,
  },
  bold: {
    fontWeight: 'bold',
  },
  footer: {
    fontSize: 14,
    marginTop: 20,
    textAlign: 'center',
  },
});

export default PayfourUyelikVeKullaniciSozlesmesi;
